changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 📢
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - new-feature
    - title: Code Improvements 🛠️
      labels:
        - improvement
    - title: Bugfixes 🐞
      labels:
        - bug-fix
    - title: Other Changes
      labels:
        - "*"