files: ^src/|^tests/
repos:
- hooks:
  - args:
    - --max-line-length=119
    - --extend-ignore=E203
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 6.1.0
- hooks:
  - args:
    - --line-length=99
    id: black
  repo: https://github.com/psf/black
  rev: 23.9.1
- hooks:
  - id: isort
    name: isort (python)
  repo: https://github.com/pycqa/isort
  rev: 5.12.0
